services:
  frontend:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
      args:
        VITE_TARGETED_URL: "http://localhost:3000/api"
    environment:
      VITE_TARGETED_URL: "http://localhost:3000/api"
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "mongodb://admin:password@mongodb:27017/ICG?authSource=admin"
      JWT_KEY: "supersecretkey"
      APP_PORT: 3000
      NODE_ENV: "production"
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: ICGmongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb-data:/data/db
    networks:
      - app-network
    ports:
      - "27017:27017"

networks:
  app-network:
    driver: bridge

volumes:
  mongodb-data:
    driver: local
